name: Generate Pacman Contribution Graph

on:
  schedule:
    # Jalankan setiap 12 jam
    - cron: '0 */12 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-pacman-graph

    steps:
      # Cukup jalankan action ini SATU KALI untuk membuat file terang dan gelap
      - name: Generate Pacman SVG
        uses: abozanona/pacman-contribution-graph@main
        with:
          github_user_name: ${{ github.repository_owner }}

      # Dorong semua file dari folder 'dist' ke branch 'output'
      - name: Push to output branch
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
